name: Deploy Image

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  push-store-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: "Checkout"
        uses: actions/checkout@main

      - name: "Login to GHCR"
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: "Build and push"
        run: |
          docker build . --tag ghcr.io/nekos-zip/nekos.zip:${{github.sha}}
          docker push ghcr.io/nekos-zip/nekos.zip:${{github.sha}}
